name: Create Release
on:
  push: 
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GH_REPO_ACCESS }}
jobs:
  generate-new-tag: 
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release 
        with:
          release-type: node
          package-name: amplience-developer-portal