name: Create Release
on:
  push: 
    branches:
      - main
jobs:
  generate-new-tag: 
    runs-on: ubuntu-latest

    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: google-github-actions/release-please-action@v3
        id: release 
        with:
          release-type: node
          package-name: amplience-developer-portal