name: Create Release
on:
  push: 
    branches:
      - main
jobs:
  generate-new-tag: 
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release 
        with:
          release-type: node
          package-name: release-please-action
          token: ${{secrets.GH_REPO_ACCESS}}